name: goodbye_app
description: "Aplicación Goodbye para gestión de despedidas digitales"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (versión unificada)
  firebase_core: ^3.14.0

  # Servicios de Firebase (versiones compatibles con core 3.x)
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_crashlytics: ^4.3.7

  # Autenticación con Google
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.1

  # Manejo de datos
  http: ^1.2.1
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  localstorage: ^6.0.0

  # UI y diseño
  google_fonts: ^6.2.1
  material_color_utilities: 0.11.1 # Versión exacta requerida por Flutter

  # Multimedia
  image_picker: ^1.1.2
  video_player: ^2.10.0
  file_picker: ^10.2.0

  # Navegación y utilidades
  go_router: ^15.2.3
  path_provider: ^2.1.2
  url_launcher: ^6.3.0
  logger: ^2.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/error_icon.png
