name: goodbye_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0-278.4.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  google_sign_in: ^6.3.0
  google_sign_in_web: ^0.12.0+3
  http: ^1.4.0
  cached_network_image: ^3.4.1
  octo_image: ^2.1.0
  leak_tracker: 10.0.9
  material_color_utilities: ^0.11.1
  vector_math: 2.1.4
  google_fonts: ^6.1.0
  image_picker: ^0.8.7+4
  go_router: ^13.0.0
  file_picker: 10.1.9
  uuid: 4.5.1
  path_provider: ^2.0.11
  url_launcher: ^6.1.11
  video_player: ^2.7.0
  video_player_web: ^2.0.16
  web: ^1.1.1
  localstorage: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  leak_tracker_testing: 3.0.1
  leak_tracker_flutter_testing: 3.0.9

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
