// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPGPtMey7IARjQE7Wouu5B9Ioyl61h_j0',
    appId: '1:1003537024990:web:77b8d3170c23ba296f3f4f',
    messagingSenderId: '1003537024990',
    projectId: 'goodbye-ae882',
    authDomain: 'goodbye-ae882.firebaseapp.com',
    storageBucket: 'goodbye-ae882.firebasestorage.app',
    measurementId: 'G-LVXCN2PE2H',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPGPtMey7IARjQE7Wouu5B9Ioyl61h_j0',
    appId: '1:1003537024990:web:7b8997451177b9af6f3f4f',
    messagingSenderId: '1003537024990',
    projectId: 'goodbye-ae882',
    authDomain: 'goodbye-ae882.firebaseapp.com',
    storageBucket: 'goodbye-ae882.firebasestorage.app',
    measurementId: 'G-4ZPXF5WJ55',
  );
}
